apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-config
  namespace: external-dns
data:
  azure.json: |
    {
      "tenantId": "1f5574e2-7e74-4fea-a5ea-8021b1b7bbca",
      "subscriptionId": "b61b10b2-15e4-43e2-8bd9-95a554e2249d",
      "resourceGroup": "rg-dns",
      "useWorkloadIdentityExtension": true
    }
