apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    chart: external-dns
    targetRevision: 1.15.0
    helm:
      values: |
        provider:
          name: azure
        priorityClassName: platform
        serviceAccount:
          create: true
          name: external-dns
          labels:
            azure.workload.identity/use: "true"
          annotations:
            azure.workload.identity/client-id: "fb9ff681-7000-44ed-b1df-ab1eaaea7f25"
        podLabels:
          azure.workload.identity/use: "true"
        extraVolumes:
          - name: azure-config
            configMap:
              name: azure-config
        extraVolumeMounts:
          - name: azure-config
            mountPath: /etc/kubernetes
            readOnly: true
        domainFilters:
          - azure.tahmidchoudhury.uk
        txtOwnerId: aks01
        policy: sync
        sources:
          - ingress
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
